---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: GithHub Super Linter

#
# Documentation:
# https://github.com/github/super-linter
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    timeout-minutes: 60

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .
          VALIDATE_BASH: true
          VALIDATE_CSS: true
          VALIDATE_DOCKER: true
          VALIDATE_GO: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_POWERSHELL: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_ISORT: true
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_YAML: true
          DISABLE_ERRORS: false
          PYTHONPATH: ${{ github.workspace }}:$PYTHONPATH
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*github/ISSUE_TEMPLATE/config.yml
#          ACTIONS_RUNNER_DEBUG: true

...
